# Generated by Django 5.0.7 on 2024-08-04 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_name_skill_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='title',
            new_name='name',
        ),
    ]
