# Generated by Django 5.0.7 on 2024-07-15 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_tag_project_vote_ratio_project_vote_total_review_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='tag',
            new_name='tags',
        ),
    ]
